---
title: "Notes"
author: "zrodnick"
date: "November 28, 2016"
output: html_document
---
These are just informal notes for myself. Read them if you want. 

##Wrangle Notes

Converted the dates from factors to date objects. Don't know how that will help, but can't think of a reason not to. 

Merged the countries metadataset with the training set. Can't think of a reason why latitude and longitude would matter for this analysis, but I'll leave them in unless I can think of a compelling reason not to. 

Created a new column that simply shows a binary trip booked or not variable. 

Creating a multiple implimentation algorithm (Mice) for filling in the NA values may be useful. Just rememeber not to use the predicted variable, destination! 

What to do with all that missing data? I could omit it, but that's a LOT of data omitted. Like more than half. I could use the Mice algorithm, but the tutorial on it says that missing more than 5% of a feature means that feature should probably be excluded. Should I just simply ignore gender as a factor? That seems wrong. 

#Variables Notes
date_account_created: Converted to date objects. Dates range from Jan 2010 to July 2014. Nothing really odd here.

timestamp_first_active: Not sure how to interpret this. It says it's a timestamp, but its just numbers in scientific notation. It should be useful, but I'm not sure what the variable is supposed to be. 

date_first_booking: This will be useful, I'm sure, but it's missing data for the NDFs. That makes sense, of course, but I'm wondering how it will mess with my analysis. 

gender: I did a preliminary logistic regression analysis between this and booked/not booked, and it showed that men and women booked trips at roughly the same amount, but people who did not list their gender booked trips at much higher rates. This suggests that people who report their gender on the website are **less** likely to book trips than people who do not report their gender. That's very odd. Additionally, people who reported their gender as "Other", while very small in number, also booked trips at much higher rates. 

age: I wonder about this variable. One would think that age would be a very significant factor in travel habits, and it very likely is, but more than half of the data is empty. There are algorithms I can use to fill in the missing data, such as the MICE algorithm, but with that much of it missing, should I really do that, or just exclude the data altogether? Also, a bunch of people listed their ages at 2014 or 1924 or something. Unless the Highlander is taking a lot of vacations, I think there's a problem here. Should I attempt to correct, or just exclude? Ask Marko. Something's screwy with this column. I hate to cut out valuable information like this, but it may need a buttload of manipulation and wrangling before it's in any shape to be analyzed, and that may render it useless. 

So there's two approaches to age: I can do a Mice, but that assumes MAR. I suspect that the data is MNAR, which is beyond my current skill level. I'll try both ways and see. MICE doesn't like categorical variables. Age is out.  

There may be something I can do here, but I'm not experienced enough for it. I'm going to cut the age column out. 

signup_method: The majority of people used the basic signup, which means through the website directly. A significant number also used facebook, and a small number used google, by which I assume they mean their Google Plus account. Have not yet checked to see if variables are related. 

signup_flow: This is supposedly the page a user arrived from, however, the data is numerical and so tells me nothing. I suppose I can just try to correlate it or something and hope it means something to somebody.

language: english is by far the most common, of course. However, it will be interesting to see if language preference predicts country language. I'll need to read more on how to conduct such an analysis, I'm still new to prediction algorithms.

affiliate_channel: What kind of paid marketing. Knowing very little about internet marketing, I'm not sure what a lot of these variables are, but they have to mean something. 

affiliate_provider: Same as above.

first_affiliate_tracked: Same as above. This contains NA data, but that only accounts for ~3% of the data, so I don't feel so bad excluding them. Also, most of the NA data comes from before 2013, which is the smallest and least reliable data. 

signup_app: Now we're getting somewhere. Only four levels, easy to analyze. I wonder how well it correlates with a lot of other variables. 

first_browser: There's a lot of little browsers here, but the ones that really matter are Chrome, Safari, Firefox, Internet Explorer, and their mobile versions. I wonder if I should compress all the little browsers into a "Misc" factor. 

country_destination: The target variable. Not surprisingly, the vast majority do not book a trip. Most that do go to the US, hardly surprising. The baseline for my prediction model should therefore be always predicting "NDF", or "US" if given that a trip is booked. 

lat, long, dist, etc: Distance to travel. Not sure how useful this will be, but data is data. From what I read, France was the most popular destination outside of the US, as opposed to English speaking countries like Britain, Canada, or Australia, so maybe destination language is not as important to international travelers. Maybe I should group international travel separately? More things to bounce off Marko!

language_levenshtein_distance and destination language: What I THINK this means is the algorithmic distance between english and the native language. This means that Dutch is most closely related to English, followed by German, and then the romance languages. This could be helpful in predicting destinations: obviously people will be more reluctant to go somewhere they don't speak the language. If only Asian countries were included in the data! Most people in Western Europe, especially the Netherlands, speak English, so that's harder to compute. 


##Manipulating Sessions_df

So what do I want to accomplish?

Group by ID - Done, can at least do that easily.
Count type and quantity of actions performed by each user
I suspect the secs_elapsed column is not in seconds, since things like 67753 secs comes out to around 18 hours. I can't see anyone spending 18 hours on the website. Milliseconds maybe? Maybe it tracks total time in between actions, not just in a single session? So somebody coming back the next day would make sense. Outliers! 

Definitely going to need some summarizing here. "Users performed action X an average of Y amount of times... etc". 

Should probably spend some time familiarizing myself with AirBnB's website. Might help with understanding. 

Holy crap there are about 1.8 million different actions the users can take. I have no idea what to do with this information. Okay, I'm dumb. Turns out there are only about 360. I have no idea what I entered to make it look like 1.8 million. That's a lot more managable. 


Possible variables for this dataset: Booked/Not booked, Number of actions till booking, device type, average time to booking (beware outliers! This is heavily skewed. Maybe use median instead). While around 360 is a lot more manageable than the millions previously thought (seriously, how did I get that?), I'm still not familiar enough with the website and business to parse out every action. I'll have to rely on aggregate statistics. 

Like what's the difference between "book" and "booking"? That kind of thing. 

##Analysis ideas

Relationship between booking language and destination?
Age vs. Destination?
Factors that lead to a non-booking?
Time of year (Especially around holidays)
Do English speakers go to more English speaking countries?

I have my suspicions that browser and computer type will be associated with age and gender. They might be interesting, but I think that age, gender, language, and source will be the more predictive factors. 

I'm going to have to make some summary statistics out of the sessions data frame. Not sure how relevant it will be, but data is data! It's pretty intimidating, and I'm not sure I know enough about web design to properly interpret it. At the very least, I can summarise it as average time spent on the website, number of actions, and booked or not.  

The fact that AirBnB allows "Other" as a gender option is very interesting! I would love to see how many people picked that as a gender option and what their travel habits are. Marketing to the trans community potentially?

I expect lots of multicolinearity within this data! This will have to be taken into account when building my model. 

Read more on multinomial logistic regression! Since I am predicting a categorical variable with more than two levels, this may be what I need. It looks like multinomial logistic regression is the way to go here, since I'm predicting a categorical variable with more than two levels. The lessons Springboard provided went over using forests and tree algorithms to predict a binary variable, but not multiple levels. Ask Marko. 


##Random Thoughts

What does levenshtein distance from the countries df mean? Maybe Marko can give me an ELI5 version. 

The number of insertions, deletions, or substitutions to get from one string to another? Huh. So is it the distance between target destination language and booking language? It's not clear. Define your variables!

Decision: I'm going to ignore the sessions data set for now and just focus on the training set. I'm still new to this after all. 
